/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ExerciseLog = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'workoutType' : IDL.Text,
  'intensity' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isActive' : IDL.Bool,
  'scheduleTime' : Time,
  'category' : IDL.Text,
});
export const WellnessLog = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'details' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferences' : IDL.Text,
  'goals' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExerciseLog' : IDL.Func([ExerciseLog], [], []),
  'addReminder' : IDL.Func([Reminder], [], []),
  'addWellnessLog' : IDL.Func([WellnessLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExerciseLog' : IDL.Func([IDL.Text], [], []),
  'deleteReminder' : IDL.Func([IDL.Text], [], []),
  'deleteWellnessLog' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExerciseLogsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(ExerciseLog)],
      ['query'],
    ),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellnessLogsByDate' : IDL.Func([Time], [IDL.Vec(WellnessLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExerciseLog' : IDL.Func([IDL.Text, ExerciseLog], [], []),
  'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
  'updateWellnessLog' : IDL.Func([IDL.Text, WellnessLog], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ExerciseLog = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'workoutType' : IDL.Text,
    'intensity' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isActive' : IDL.Bool,
    'scheduleTime' : Time,
    'category' : IDL.Text,
  });
  const WellnessLog = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'details' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferences' : IDL.Text,
    'goals' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExerciseLog' : IDL.Func([ExerciseLog], [], []),
    'addReminder' : IDL.Func([Reminder], [], []),
    'addWellnessLog' : IDL.Func([WellnessLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExerciseLog' : IDL.Func([IDL.Text], [], []),
    'deleteReminder' : IDL.Func([IDL.Text], [], []),
    'deleteWellnessLog' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExerciseLogsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(ExerciseLog)],
        ['query'],
      ),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellnessLogsByDate' : IDL.Func(
        [Time],
        [IDL.Vec(WellnessLog)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExerciseLog' : IDL.Func([IDL.Text, ExerciseLog], [], []),
    'updateReminder' : IDL.Func([IDL.Text, Reminder], [], []),
    'updateWellnessLog' : IDL.Func([IDL.Text, WellnessLog], [], []),
  });
};

export const init = ({ IDL }) => { return []; };