/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExerciseLog {
  'id' : string,
  'date' : Time,
  'durationMinutes' : bigint,
  'notes' : string,
  'workoutType' : string,
  'intensity' : string,
}
export interface Reminder {
  'id' : string,
  'title' : string,
  'isActive' : boolean,
  'scheduleTime' : Time,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'preferences' : string,
  'goals' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessLog {
  'id' : string,
  'date' : Time,
  'details' : string,
  'category' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExerciseLog' : ActorMethod<[ExerciseLog], undefined>,
  'addReminder' : ActorMethod<[Reminder], undefined>,
  'addWellnessLog' : ActorMethod<[WellnessLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExerciseLog' : ActorMethod<[string], undefined>,
  'deleteReminder' : ActorMethod<[string], undefined>,
  'deleteWellnessLog' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExerciseLogsByDateRange' : ActorMethod<[Time, Time], Array<ExerciseLog>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWellnessLogsByDate' : ActorMethod<[Time], Array<WellnessLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExerciseLog' : ActorMethod<[string, ExerciseLog], undefined>,
  'updateReminder' : ActorMethod<[string, Reminder], undefined>,
  'updateWellnessLog' : ActorMethod<[string, WellnessLog], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];